---
all:
  vars:
    tailscale_authkey: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      33343464353565343435326333373030653633663035313230303161626130353238613036326164
      6130356662356135326630366231303736326134623639610a306639613433353038646562616135
      63303634363732306163336164663064383833326634393262396331313536313361663131363139
      6435646133366334370a396132386633623034346239613238356330336638383365336139383139
      61626530343130383139376539356266656633386639666335636364646430643630636535363039
      61306465643462336131373730306238316633386561663437336630613535363136366261616463
      643432643231356231336363313833316233
    tailscale_up_skip: false
    insecurely_log_authkey: true
    tailscale_args: "--ssh"
    tailscale_oauth_ephemeral: false
    tailscale_tags:
      - homelab

  children:
    k3s_cluster:
    standalone_pis:
    jitsi:
  hosts:
    lyn:
    hole:

jitsi:
  hosts:
    meet:
      ansible_host: meet
      ansible_user: root
      tailscale_tags:
        - core-services
        - o11y-agent
prod:
  hosts:
    hole:
      ansible_host: hole.elbschloss.xyz
      ansible_user: root
      tailscale_tags:
        - core-infra
        - core-services
      tailscale_args: "--ssh --advertise-exit-node"
    synology:
      ansible_host: nas
      ansible_user: king
      tailscale_tags:
        - core-infra
        - core-services
    nuc:
      ansible_host: nuc
      ansible_user: root
      tailscale_tags:
        - core-infra
        - o11y-collector

standalone_pis:
  hosts:
    jumphost:
      ansible_host: jumphost.local
      tailscale_tags:
        - homelab
        - jumphost
    lora:
      ansible_host: lora.local
    timepi-gps:
      ansible_host: timepi-gps
      ansible_user: cedi
      rpi_enable_uart: true
      rpi_additional_dtparam:
        - i2c_arm=on
        - i2s=on
        - spi=on
        - uart0=on
      rpi_dtoverlays:
        - pps-gpio,gpiopin=18
      rpi_cmdline_params_removed:
        - console=serial0,115200

raspberry_pis:
  vars:
    ansible_user: pi
    node_exporter_arch: arm64
  children:
    k3s_cluster:
    standalone_pis:
    ceph_cluster:
    compute_blades:

raspberry_pi_4:
  vars:
    rpi_fan_trip_points:
      poe_fan_temp0: 65000
      poe_fan_temp1: 70000
      poe_fan_temp2: 75000
      poe_fan_temp3: 80000
    rpi_dtoverlays:
      - rpi-poe-plus
  hosts:
    clusterpi-worker1:
    clusterpi-worker2:
    clusterpi-worker3:
    clusterpi-worker4:
    lora:

raspberry_pi_5:
  vars:
    rpi_fan_trip_points:
      fan_temp0: 65000
      fan_temp1: 70000
      fan_temp2: 75000
      fan_temp3: 80000
    rpi_pciex1_gen: 3
  children:
    ceph_cluster:
  hosts:
    clusterpi-leader:
    lyv:
    timepi-gps:

ceph_cluster:
  hosts:
    storagepi-ceph1:
      ansible_host: storagepi-ceph1
    storagepi-ceph2:
      ansible_host: storagepi-ceph2
    storagepi-ceph3:
      ansible_host: storagepi-ceph3

compute_blades:
  hosts:
    blade-pi1:
      ansible_host: blade-pi1.local
    blade-pi2:
      ansible_host: blade-pi2.local
    blade-pi3:
      ansible_host: blade-pi3.local
    blade-pi4:
      ansible_host: blade-pi4.local

k3s_cluster:
  vars:
    extra_server_args: "--disable-network-policy --disable traefik"
    extra_agent_args: ""
    k3s_version: v1.31.1+k3s1
    cluster_context: labk3s
    kubeconfig: ~/.kube/configs/labk3s
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    token: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      36656164376163613637356330623533323062383639346231656132393732636434336232653265
      3138313531386637306162376632663663346535333432360a333132646137343539656633636133
      35306131356637383433663363396631323731383030633239666466636462373235663463353136
      6133666463343461390a356535343336336132623365646531323763623435356530316235363063
      64656538336237653838343534663939653333333562633364626236613764313332
  children:
    server:
      hosts:
        clusterpi-leader:
          ansible_host: clusterpi-leader
    agent:
      hosts:
        clusterpi-worker1:
          ansible_host: clusterpi-worker1
        clusterpi-worker2:
          ansible_host: clusterpi-worker2
        clusterpi-worker3:
          ansible_host: clusterpi-worker3
        clusterpi-worker4:
          ansible_host: clusterpi-worker4
