---
- name: Install Ubuntu Raspi Extra Packages
  ansible.builtin.apt:
    # Fixes issues in newer Ubuntu where VXLan isn't setup right.
    # See: https://github.com/k3s-io/k3s/issues/4234
    name: linux-modules-extra-raspi
    update_cache: true
    state: present
  when: "ansible_distribution_version is version('20.10', '>=') and ansible_distribution_version is version('24.04', '<')"
