---
- name: Check if /boot/firmware/cmdline.txt exists
  ansible.builtin.stat:
    path: /boot/firmware/cmdline.txt
  register: boot_firmware_cmdline_txt

- name: Enable cgroup via boot commandline if not already enabled
  ansible.builtin.replace:
    path: "{{ (boot_firmware_cmdline_txt.stat.exists) | ternary('/boot/firmware/cmdline.txt', '/boot/cmdline.txt') }}"
    regexp: '^([\w](?!.*\b{{ cgroup_item }}\b).*)$'
    replace: '\1 {{ cgroup_item }}'
  with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
  loop_control:
    loop_var: cgroup_item
  notify: Reboot Pi

- name: Set Pi model specific firmware parameter
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "firmware/raspberry_pi_{{ raspberry_pi_version }}.yml"
    - "prereq/default.yml"
  when:
    - raspberry_pi|default(false)
