---
- name: Detect Raspberry Pi Version and Model
  ansible.builtin.include_tasks: "pi-version.yml"

- name: Detect Raspberry Pi OS
  ansible.builtin.include_tasks: "os-detection.yml"

- name: Configure RaspberryPi Firmware
  ansible.builtin.include_tasks: "firmware-config.yml"
  when:
    - raspberry_pi|default(false)

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Execute OS related tasks on the Raspberry Pi
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "prereq/{{ detected_distribution }}.yml"
    - "prereq/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "prereq/{{ ansible_distribution }}.yml"
    - "prereq/default.yml"
  when:
    - raspberry_pi|default(false)

- name: Install rpi-clone
  become: true
  when:
    - raspberry_pi|default(false)
    - raspberry_pi_version == 5
  block:
    - name: Clone rpi-clone repository
      git:
        repo: "https://github.com/geerlingguy/rpi-clone.git"
        dest: "~/rpi-clone"
        clone: true
        update: true
        recursive: true

    - name: Install rpi-clone
      command: "sudo cp rpi-clone rpi-clone-setup /usr/local/sbin"
      args:
        chdir: "~/rpi-clone"
