---
- name: Detect Raspberry Pi Version and Model
  ansible.builtin.include_tasks: "pi-version.yml"

- name: Detect Raspberry Pi OS
  ansible.builtin.include_tasks: "os-detection.yml"

- name: Configure RaspberryPi Firmware
  ansible.builtin.include_tasks: "firmware-config.yml"
  when:
    - raspberry_pi|default(false)

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Execute OS related tasks on the Raspberry Pi
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "prereq/{{ detected_distribution }}.yml"
    - "prereq/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "prereq/{{ ansible_distribution }}.yml"
    - "prereq/default.yml"
  when:
    - raspberry_pi|default(false)
