---
- name: Set detected_distribution to Raspbian
  ansible.builtin.set_fact:
    detected_distribution: Raspbian
  when: >
    raspberry_pi|default(false) and
    ( ansible_facts.lsb.id|default("") == "Raspbian" or
      ansible_facts.lsb.description|default("") is match("[Rr]aspbian.*") )

- name: Set detected_distribution to Debian
  ansible.builtin.set_fact:
    detected_distribution: Debian
  when: >
    raspberry_pi|default(false) and
    ( ansible_facts.lsb.id|default("") == "Debian" or
      ansible_facts.lsb.description|default("") is match("Debian") )

- name: Set detected_distribution to ArchLinux (ARM64)
  ansible.builtin.set_fact:
    detected_distribution: Archlinux
  when:
    - ansible_facts.architecture is search("aarch64")
    - raspberry_pi|default(false)
    - ansible_facts.os_family is match("Archlinux")
