---
- name: Configure hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ base__locales }}"

- name: Place language choice
  copy:
    owner: root
    group: root
    mode: 0644
    content: "export LANG={{ base__lang }}"
    dest: /etc/profile.d/lang.sh
