---
- name: Clone repo with install script
  loop: "{{ base__installer_from_git }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    clone: true
    update: true
    recursive: true

- name: Run the installer script
  command: "{{ item.command }}"
  loop: "{{ base__installer_from_git }}"
  args:
    chdir: "{{ item.dest }}"
