- name: download installer scripts
  loop: "{{ base__installer_scripts }}"
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}"
    mode: "+x"

- name: run intaller scripts
  loop: "{{ base__installer_scripts }}"
  when: item.args is not defined | default(false) | bool
  command: "bash /tmp/{{ item.name }}"
  args:
    creates: "{{ item.creates }}"

- name: run intaller scripts
  loop: "{{ base__installer_scripts }}"
  when: item.args is defined | default(false) | bool
  command: "bash /tmp/{{ item.name }} {{ item.args }}"
  args:
    creates: "{{ item.creates }}"
