version: "3.9"

services:
  node-exporter:
    image: prom/node-exporter:latest
    command:
      - --collector.disable-defaults
      - --collector.stat
      - --collector.time
      - --collector.cpu
      - --collector.loadavg
      - --collector.hwmon
      - --collector.meminfo
      - --collector.diskstats
    container_name: NodeExporter
    hostname: node_exporter
    network_mode: host
    mem_limit: 256m
    mem_reservation: 64m
    cpu_shares: 512
    security_opt:
      - no-new-privileges=true
    ports:
      - "9100:9100"
    read_only: true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9100/
    restart: unless-stopped

  snmp-exporter:
    image: prom/snmp-exporter:latest
    command:
      - "--config.file=/etc/snmp_exporter/snmp.yml"
    container_name: SNMPExporter
    hostname: snmp
    network_mode: host
    mem_limit: 256m
    mem_reservation: 64m
    cpu_shares: 512
    security_opt:
      - no-new-privileges:true
    read_only: true
    ports:
      - "9116:9116"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9116/ || exit 1
    volumes:
      - /volume1/docker/o11y/snmp-exporter/snmp.yaml:/etc/snmp_exporter/snmp.yml:ro
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    command:
      - "--docker_only=true"
      - "--port=8123"
    container_name: cAdvisor
    hostname: cadvisor
    network_mode: host
    mem_limit: 256m
    mem_reservation: 64m
    cpu_shares: 512
    security_opt:
      - no-new-privileges=true
    ports:
      - "8123:8123"
    read_only: true
    environment:
      - CADVISOR_HEALTHCHECK_URL=http://localhost:8123/healthz
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  # alloy:
  #   image: grafana/alloy:latest
  #   container_name: alloy
  #   restart: unless-stopped
  #   network_mode: host
  #   command:
  #     - "run"
  #     - "--server.http.listen-addr=0.0.0.0:12345"
  #     - "--storage.path=/var/lib/alloy/data"
  #     - "/etc/alloy/config.alloy"
  #   ports:
  #     - "12345:12345"
  #   volumes:
  #     - /volume1/docker/o11y/alloy/config.alloy:/etc/alloy/config.alloy
