---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: k3s/prereq
    - role: k3s/airgap

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - role: k3s/server

- name: Setup K3S agent
  hosts: agent
  become: true
  roles:
    - role: k3s/agent
