---
- name: Set up NUT Server
  hosts: nuc
  become: true
  gather_facts: true
  roles:
    - nut_server

- name: Set up NUT Client
  hosts:
    - raspberry_pis
  become: true
  gather_facts: true
  roles:
    - geerlingguy.nut_client

- name: Apply NUT shutdown behavior
  hosts:
    - raspberry_pis
  become: true
  roles:
    - role: nut_shutdown_behavior
